### ISSUE TITLE
main website, sample mesh page

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/Pressio.github.io#10]
- sample mesh:
  - [ ] find figures to show
  - [ ] any edits to clarify things
  - [ ] references

**Comment by pjb236** [comment]
Where should the sample mesh page go in the main website? I don't remember what we decided on.

**Comment by fnrizzi** [comment]
@pjb236 i don't remember either :) 
let's talk about it later, but please you use the `issues3_and_6` branch. I think if you open that, it should be clear where to put it. 

Btw, we can use the scripts in pressio-demoapps to generate sample mesh figures. But also using the figs from Blottner etc, it would be nice.

**Comment by eparish1** [comment]
For hyper-reduction, I think we could either just beef up the page that we have right now in the issues_3_and_6 branch with more details and figures, or we could keep that page as is and add a link to it to more details about hyper-reduction. If we took this latter approach, I think we could add a link on the main page under overview that talks about hyper-reduction. I think this would be reasonably scoped here since hyper-reduction is a core part of making our stuff work

**Comment by pjb236** [comment]
Got it, will start working on this today!

**Comment by pjb236** [comment]
@fnrizzi @eparish1 , please review what I have so far and let me know what else is needed. If it looks good, then we can close this issue.

**Comment by fnrizzi** [comment]
@pjb236 working on it now!

**Comment by fnrizzi** [comment]
@pjb236 it was great! 
i made some edits and merged into develop and main. IMMO, I think it would be nice to provide a more detailed description of the difference between sample mesh and hyper-reduction. What I mean is to discuss that sample mesh is needed for hype-reduction, but these two things should not be confused one with the other. 
More specifically, I think here: 

*How does Pressio support hyper-reduction?
Hyperreduction is composed of two aspects. First, hyper-reduction places a burden on the application to only compute the velocity/residual on the sample mesh. As this burden is on the application, Pressio is unable to provide this functionality to a code. The second aspect of hyper-reduction is a modification to the underlying pROM problem. Pressio has support for this aspect of hyper-reduction, as it is application agnostic. *

I think here we could use more discussion on how hr is useful to approximate operators, etc. 
But I think for now what we have is enough, so we should move on to #12 and revisit this later!
