### ISSUE TITLE
add tab to list work/usecases: basically a "business card" tab for pressio

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/Pressio.github.io#12]

**Comment by pjb236** [comment]
Here what I'm thinking for each use case:

1. Brief explanation of the use case
2. Picture showing FOM solution
3. Picture showing ROM solution
4. Picture of sample mesh
5. Some performance numbers

Please let me know if this is consistent with what you had in mind.

**Comment by fnrizzi** [comment]
@pjb236 yes, this is great!
Just to make sure that in the explanation, we also discuss why the usecase might be important/useful.

**Comment by pjb236** [comment]
The rough draft for the Blottner sphere results is ready for you to look at @fnrizzi . I'll reach out to AIAA to determine policies on reusing figures from their papers.

**Comment by fnrizzi** [comment]
@pjb236 thanks for making the page, I like how it is shaping up!
I made some edits: 
-  split the portfolio into two pages: Blottner and HiFire to handle separate things. I think it is better to have a single page focus on a single problem. 
- i made some changes to figure and general layout.

A few more suggestions: 
- in the ROM section, can you please give more details on which ROM method we use 
- it would be nice to also put links to the code functionalities of pressio that correspond to them (I can do this if you want)
- as is, the computational cost advantages are not discussed. I would add one paragraph near the end and call it `take home message` where we use colors to emphasize two things:  (1) the accuracies (which you already mention but are not emphasized enough) and (2) computational cost comparison. So basically, if i jump on this page, I would like the eye of the reader to fall on the `take home message`. 
- can you please also link the arxiv pressio paper? just to show there is a paper with this.
Thanks!

**Comment by pjb236** [comment]
@fnrizzi Thank you for the suggestions, I will start working on these!
